/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Resource {
  'title' : string,
  'description' : string,
  'seller' : Principal,
  'resourceType' : ResourceType,
  'price' : bigint,
}
export type ResourceType = { 'video' : null } |
  { 'guide' : null } |
  { 'notes' : null };
export interface UserProfile {
  'branch' : string,
  'semester' : bigint,
  'name' : string,
  'year' : bigint,
  'email' : string,
  'college' : string,
}
export interface _SERVICE {
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserResources' : ActorMethod<[Principal], Array<Resource>>,
  'listResource' : ActorMethod<
    [string, string, ResourceType, bigint],
    undefined
  >,
  'registerUser' : ActorMethod<
    [string, string, string, bigint, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];