/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResourceType = IDL.Variant({
  'video' : IDL.Null,
  'guide' : IDL.Null,
  'notes' : IDL.Null,
});
export const Resource = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'resourceType' : ResourceType,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'branch' : IDL.Text,
  'semester' : IDL.Nat,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'email' : IDL.Text,
  'college' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserResources' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Resource)],
      ['query'],
    ),
  'listResource' : IDL.Func(
      [IDL.Text, IDL.Text, ResourceType, IDL.Nat],
      [],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResourceType = IDL.Variant({
    'video' : IDL.Null,
    'guide' : IDL.Null,
    'notes' : IDL.Null,
  });
  const Resource = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'resourceType' : ResourceType,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'branch' : IDL.Text,
    'semester' : IDL.Nat,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'email' : IDL.Text,
    'college' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserResources' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'listResource' : IDL.Func(
        [IDL.Text, IDL.Text, ResourceType, IDL.Nat],
        [],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };